
# General configuration ––––––––––––––––––––––––––––––––––––––––
output_file: "output_test.csv"
solver_type: "Explicit"  # Choose between "Implicit" or "Explicit"

# OdeSolver settings
OdeSolver:
  step_size: 0.01
  initial_time: 0.0
  final_time: 1.0
  initial_value: [0.0, 1.0, 0.0]


# Explicit solver settings ––––––––––––––––––––––––––––––––––––––––
Explicit:
  method: "ForwardEuler"  # Choose between "ForwardEuler", "RungeKutta", "AdamsBashforth"
  #if method is "RungeKutta"
  RungeKutta:
    order: 4  # Choose between 1, 2, 3, 4
    #if not order
    coefficients:
      a: 
        - [0.0, 0.0, 0.0, 0.0]
        - [0.5, 0.0, 0.0, 0.0]
        - [0.0, 0.5, 0.0, 0.0]
        - [0.0, 0.0, 0.5, 0.0]
      b: [0.16666666666667, 0.33333333333333, 0.33333333333333, 0.16666666666667]
      c: [0.0, 0.5, 0.5, 1.0]

  #if method is "AdamsBashforth"
  AdamsBashforth:
    max_order: 4 # Choose between 1, 2, 3, 4
    #if NOT max_order
    coefficients_vector: [55/24.0, -59/24.0, 37/24.0, -9/24.0]


# Implicit solver settings ––––––––––––––––––––––––––––––––––––––––
Implicit:
  method: "BackwardEuler"  # Choose between "BackwardEuler" (or "CrankNicolson")
  rhs_is_linear: true 
  linear_system_solver: "GaussianElimination"  # Choose between "GaussianElimination" (or "LU")
  # if rhs is linear :y' = Ay + b
  rhs_system:         
    A: 
      - [1.0, 0.0, 0.0]
      - [0.0, 1.0, 0.0]
      - [0.0, 0.0, 1.0]
    b: [0.0, 0.0, 0.0]
  # if rhs is NOT linear 
  tolerance: 1e-6
  max_iterations: 100
  root_finder: "NewtonRaphson"  # Choose between "NewtonRaphson" (or "FixedPoint")
  dx : 1e-6 # for NewtonRaphson (or methods that use numerical differentiation)
