
# General configuration ––––––––––––––––––––––––––––––––––––––––
output_file: "output_test_ExplFwdEuler.csv"
solver_type: "Explicit"  # Choose between "Implicit" or "Explicit"

# OdeSolver settings
OdeSolver:
  step_size: 0.01
  initial_time: 0.0
  final_time: 1.0
  initial_value: [1.0, 1.0, 0.0]


# Explicit solver settings ––––––––––––––––––––––––––––––––––––––––
Explicit:
  method: "ForwardEuler"  # Choose between "ForwardEuler", "RungeKutta", "AdamsBashforth"
  #if method is "RungeKutta"
  RungeKutta:
    order:  # Choose between 1, 2, 3, 4
    #if not order
    coefficients:
      a:
      b:
      c:

  #if method is "AdamsBashforth"
  AdamsBashforth:
    max_order: # Choose between 1, 2, 3, 4
    #if NOT max_order
    coefficients_vector:


# Implicit solver settings ––––––––––––––––––––––––––––––––––––––––
Implicit:
  method:  # Choose between "BackwardEuler" (or "CrankNicolson")
  rhs_is_linear:
  linear_system_solver:  # Choose between "GaussianElimination" (or "LU")
  # if rhs is linear :y' = Ay + b
  rhs_system:         
    A:
    b:
  # if rhs is NOT linear 
  tolerance:
  max_iterations:
  root_finder:  # Choose between "NewtonRaphson" (or "FixedPoint")
  dx : # for NewtonRaphson (or methods that use numerical differentiation)
